const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const elements={};
const chartContext=vm.createContext({structuredClone,localStorage:{getItem:()=>null},document:{addEventListener(){}}});
vm.runInContext(fs.readFileSync('webui/static/chart_workbench.js','utf8')+'\nthis.workbench=ChartWorkbench;',chartContext);
const context=vm.createContext({document:{addEventListener(){},getElementById:id=>elements[id]}});
let applied;
context.ChartWorkbench={validateSettings:chartContext.workbench.validateSettings,applySettings:x=>applied=x,getSettings:chartContext.workbench.getSettings};
context.Event=class {constructor(type){this.type=type;}};
vm.runInContext(fs.readFileSync('webui/static/presets.js','utf8')+'\nthis.presets=KronosPresets;',context);
const original={version:1,name:'Portable',controls:{'device-select':'cuda','live-horizon':'160',POLYGON_API_KEY:'excluded'},chart:{height:500,mas:[{type:'EMA',period:21,color:'#38bdf8'}]}};
const validated=context.presets.validate(original);
assert.equal(validated.controls.POLYGON_API_KEY,undefined);
assert.equal(validated.chart.mas[0].period,21);
assert.throws(()=>context.presets.validate({...original,version:2}));
assert.throws(()=>context.presets.validate({...original,name:''}));
assert.throws(()=>context.presets.validate({...original,chart:null}));
elements['device-select']={tagName:'SELECT',value:'mps',options:[{value:'mps'},{value:'cuda',disabled:true}],dispatchEvent(){}};
elements['live-horizon']={tagName:'INPUT',type:'number',min:'1',max:'512',value:'120',dispatchEvent(){}};
assert.deepEqual([...context.presets.apply(validated)],['device-select']);
assert.equal(elements['device-select'].value,'mps');assert.equal(elements['live-horizon'].value,'160');assert.equal(applied.height,500);
elements['live-horizon'].value='120';
assert.deepEqual([...context.presets.apply({...validated,controls:{'live-horizon':'99999'}})],['live-horizon']);
assert.equal(elements['live-horizon'].value,'120');
console.log('Preset schema, credential exclusion, chart settings, platform device and context limits passed.');
